---
title: "Topic Modelling of Whole Data - PA"
author: "Kavish Tyagi"
date: "January 31, 2019"
output: word_document
---

## Topic Modelling
```{r}
library(lime)
library(xgboost) # the classifier
library(text2vec) # used to build the BoW matrix
library(plyr)
library(magrittr)
library(lattice)
library(ggplot2)
library(caret)
library(stopwords)
library(tidyr)
library(topicmodels)
library(tm)
library(tidytext)
library(dplyr)
```



```{r}
article_df = read.csv('Political Articles.csv')
#article_df$Post.Text = as.character(article_df$Post.Text) 
article_df$article_all = (as.String(article_df$Post.Text))

article_corp = iconv(article_df$Post.Text, to = "utf-8")


corpus_text = VCorpus(VectorSource(article_corp))
stop_total = stopwords("en")

corpus_clean =  corpus_text %>%
  tm_map (tolower) %>%
  tm_map (removeWords, stop_total) %>%
  tm_map (removeNumbers)  %>%
  tm_map (stripWhitespace) %>%
  tm_map (PlainTextDocument)
```
```{r}
dtm_text = DocumentTermMatrix(corpus_clean)

text_lda = LDA(dtm_text, k = 10, control = list(seed = 123))
```
```{r}
text_topics <- tidy(text_lda, matrix = "beta")
text_topics

text_top_terms <- text_topics %>%
  group_by(topic) %>%
  top_n(10, beta) %>%
  ungroup() %>%
  arrange(topic, -beta)

text_top_terms %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip()
```


